POST http://localhost:5000/tracks
Content-Type: application/json

{
  "name": "New Track",
  "description": "New Description"
}


PUT http://localhost:5000/tracks/1
Content-Type: application/json

{
  "name": "Updated Track",
  "description": "Updated Description"
}

DELETE http://localhost:5000/tracks/1